// Crawlee-style request queue for MV3 service worker.
// Dedup by canonical URL, depth tracking, per-origin adaptive rate limit,
// retry with exponential backoff on 429/503 + Retry-After parsing.
// No external deps; runs inside the SW.

// ──────────────────────────────────────────────────────────────────────
// Crawl-gate filter. URLs matching these are never enqueued regardless of
// where they were discovered (sitemap, nav, feed, hreflang, body-link).
// PDF is intentionally NOT in the blocked extensions — we crawl PDFs since
// they're in-scope for a full site accessibility audit. Images / video /
// audio / spreadsheets / docs / archives / fonts / code / installers are
// all skipped.
//
// Path-prefix blocks cover WordPress admin + machine endpoints that either
// require login (no rendered page to audit) or are non-HTML RPC/JSON.
// Adding to these arrays is the single place to extend the block list.
// ──────────────────────────────────────────────────────────────────────
const NON_CRAWLABLE_EXT = new Set([
  // Images
  "png", "jpg", "jpeg", "gif", "svg", "ico", "webp", "avif", "bmp", "tiff", "tif", "heic", "heif",
  // Video
  "mp4", "webm", "m4v", "mkv", "avi", "mov", "wmv", "flv", "ogv", "3gp",
  // Audio
  "mp3", "wav", "m4a", "flac", "ogg", "opus", "aac", "wma",
  // Office (EXCEPT pdf — we crawl PDFs)
  "xls", "xlsx", "xlsm", "xlsb", "csv", "tsv", "ods",
  "doc", "docx", "dot", "dotx", "odt", "rtf",
  "ppt", "pptx", "odp",
  // Archives
  "zip", "tar", "gz", "bz2", "7z", "rar", "br", "xz",
  // Fonts
  "woff", "woff2", "ttf", "otf", "eot",
  // Code / data
  "js", "mjs", "css", "json", "xml", "txt", "map", "yaml", "yml",
  // Binaries / installers
  "exe", "dmg", "msi", "apk", "ipa", "pkg", "deb", "rpm", "iso", "bin"
]);

const BLOCKED_PATH_PREFIXES = [
  // WordPress admin + machine endpoints
  "/wp-admin",
  "/wp-json",
  "/wp-login.php",
  "/xmlrpc.php",
  "/wp-cron.php",
  "/wp-trackback.php",
  "/wp-comments-post.php",
  // WordPress archive / auto-generated chaff that a human browsing the
  // site menu does not visit. These routes are created by WordPress for
  // every author, tag, category, uploaded image (attachment), paged
  // archive, and comment feed — on a medium site that's thousands of
  // near-duplicate pages which the site owner did not hand-author and
  // which a normal visitor would never discover through the nav. They
  // flood the sitemap and burn the URL budget on noise.
  //   /author/<slug>         — per-author post listings
  //   /tag/<slug>            — per-tag listings (autogenerated)
  //   /category/<slug>       — per-category listings (autogenerated)
  //   /attachment/<slug>     — image "attachment" wrapper pages (the
  //                            "images as links to pages that aren't on
  //                            the site" symptom: WP wraps every uploaded
  //                            image in an HTML page with its own URL)
  //   /page/<N>              — archive pagination (/blog/page/2, /page/3…)
  //   /feed, /comments/feed  — RSS/Atom XML, not audit targets
  //   /?replytocom=          — reply-to-comment anchors masquerading as URLs
  // A site owner who explicitly wants these audited can still reach them
  // via the `seed` source which bypasses this gate.
  "/author",
  "/tag",
  "/category",
  "/attachment",
  "/feed",
  "/comments/feed",
  // Popup Builder plugin — exposes modal-config URLs like
  // /popupbuilder/<popup-slug>. These are NOT pages a human visits;
  // they're the plugin's internal endpoints for configured popups.
  // Commonly errors out on scan ("(error)" suffix) or renders the
  // same redirected landing page for every slug.
  "/popupbuilder",
  // Generic
  "/cgi-bin"
];

// Custom Post Type taxonomy archives. WordPress lets plugins/themes
// register their own taxonomies (e.g. Portfolio CPT → /portfolio-category/,
// /portfolio-tag/; Products CPT → /product-category/; Video CPT →
// /video-category/, /video-tag/). These are autogenerated archive pages
// the site owner never wrote — same audit problem as /category/ and
// /tag/. Match first-path-segment ending in "-category" or "-tag" OR
// equal to "video-tag" / "video-category" style bare segments.
//   /portfolio-category/creative  → blocked
//   /video-tag                    → blocked
//   /products-tag/new             → blocked
//   /tagline                      → NOT blocked (doesn't end in -tag/-category)
//   /our-category-of-services     → NOT blocked (not the first segment)
const CPT_TAXONOMY_RX = /^\/[a-z0-9][a-z0-9-]*-(?:category|tag)(?:\/|$)/i;

// WordPress archive-pagination pattern. `/page/<N>` appears nested inside
// any archive path — `/blog/page/2`, `/news/page/10`, `/category/foo/page/3`.
// Prefix matching can't catch a nested segment, so we check this with a
// regex anywhere in the path. `/page/1` is also a duplicate of the parent
// archive page so we strike it too.
const WP_PAGE_PAGINATION_RX = /\/page\/\d+\/?$/i;

// "The Gem" theme / "Gem Team" plugin CPT taxonomy endpoints. The plugin
// registers its taxonomies as `/tgr_member_<taxonomy>` (underscores, not
// dashes — so CPT_TAXONOMY_RX above doesn't catch them). Examples:
//   /tgr_member_filters/<slug>   — filter-group archive
//   /tgr_member_fields/<slug>    — "fields of expertise" archive
//   /tgr_member_skills/<slug>    — skills archive
// All autogenerated, never hand-authored, and on the sites we've observed
// they return 500/error pages. Block the entire `/tgr_member_*` family
// with a regex (prefix-string matching can't match variable suffixes
// after an underscore).
const TGR_MEMBER_RX = /^\/tgr_member_/i;

// Query-string patterns that indicate non-authored / machine / duplicate
// routes. Human-browsable pages never look like these; they're WP's
// fallback "pretty permalinks off" shape plus comment-reply anchors.
//   ?p=NNN              — WP post ID permalink fallback (duplicate of the
//                         pretty URL)
//   ?page_id=NNN        — WP page ID permalink fallback
//   ?attachment_id=NNN  — WP attachment ID permalink (another image
//                         wrapper page)
//   ?cat=NNN            — WP category ID fallback
//   ?tag=SLUG           — WP tag ID fallback
//   ?author=NNN         — WP author archive fallback
//   ?replytocom=NNN     — "Reply to this comment" anchor param
//   ?share=…            — social-share button URL (no unique content)
//   ?print=…            — print view of an already-crawled page
// Matched as `param in u.searchParams` (presence only, value-agnostic).
const BLOCKED_QUERY_PARAMS = new Set([
  "p", "page_id", "attachment_id", "cat", "tag", "author",
  "replytocom", "share", "print",
  // Modal / dialog / popover state encoded in the URL. These are
  // anchor-triggered overlays — /portfolio?open=Xpedize opens a
  // modal on the /portfolio page, it is NOT a separate destination.
  // Sites using this pattern generate one fake "page" per card
  // (15+ portfolio entries, 3+ news entries, etc.) every one of
  // which lands on the same underlying page (fingerprint dedup
  // catches the rendered ones; enqueue-block catches the rest,
  // including the ones that 404 because the server can't handle
  // the direct hit).
  // `show` is deliberately NOT added — it's ambiguous (e.g.
  // `?show=all` for filter state is legit).
  "open", "modal", "dialog", "popup", "popover"
]);

// Placeholder href patterns. Some JS frameworks / CMS plugins render
// unbound template fragments directly into the nav DOM — strings like
// `/team/member_7d84d8bf` or `/insights/item_4db2c79f` where the hex
// suffix is a build-time placeholder that was never replaced with a
// real slug. The server 404s them; the crawler burns a URL slot and
// a tab-open on each. Pattern: a path segment ending in
// `_<6+ hex digits>` (always hex, never decimal — rules out real
// slugs like `/articles/report-2024`). Match is on the last path
// segment only so we never over-match something like `/press_release`
// (no hex suffix).
const PLACEHOLDER_HEX_RX = /^[A-Za-z][A-Za-z0-9-]*_[0-9a-f]{6,}$/;

export function isCrawlablePath(urlString) {
  let u;
  try { u = new URL(urlString); } catch { return false; }
  const path = u.pathname.toLowerCase();

  // Extension check against the last segment only. `/foo.png/bar` is a
  // valid HTML path (basename has no dot), so we check basename, not path.
  const lastSlash = path.lastIndexOf("/");
  const basename = lastSlash >= 0 ? path.slice(lastSlash + 1) : path;
  const dot = basename.lastIndexOf(".");
  if (dot > 0) {
    const ext = basename.slice(dot + 1);
    if (NON_CRAWLABLE_EXT.has(ext)) return false;
  }

  // Placeholder-hex basename (see PLACEHOLDER_HEX_RX definition above).
  if (basename && PLACEHOLDER_HEX_RX.test(basename)) return false;

  // Path-prefix check. Match if the path equals the prefix, OR begins with
  // "<prefix>/…", OR begins with "<prefix>?…" (bare-file admin endpoints
  // like /wp-login.php often have query strings).
  for (const pre of BLOCKED_PATH_PREFIXES) {
    if (path === pre || path.startsWith(pre + "/") || path.startsWith(pre + "?")) return false;
  }

  // Archive pagination — nested anywhere in the path, e.g. /blog/page/2.
  if (WP_PAGE_PAGINATION_RX.test(path)) return false;

  // CPT taxonomy archives — /portfolio-category/, /video-tag, etc.
  if (CPT_TAXONOMY_RX.test(path)) return false;

  // The Gem theme's tgr_member_* taxonomy endpoints.
  if (TGR_MEMBER_RX.test(path)) return false;

  // Query-string patterns. Presence of any blocked param marks the URL
  // as machine-fallback chaff even if the path itself looks clean —
  // e.g. /?p=123 has path "/" (innocent) but the query makes it a
  // WordPress post-ID fallback that duplicates the pretty permalink.
  for (const k of u.searchParams.keys()) {
    if (BLOCKED_QUERY_PARAMS.has(k.toLowerCase())) return false;
  }

  return true;
}

export function canonicalize(raw, base) {
  try {
    const u = new URL(raw, base);
    if (u.protocol !== "http:" && u.protocol !== "https:") return null;
    u.hash = "";
    // Strip default ports
    if ((u.protocol === "http:" && u.port === "80") ||
        (u.protocol === "https:" && u.port === "443")) u.port = "";
    // Collapse trailing slash except for root
    if (u.pathname.length > 1 && u.pathname.endsWith("/")) {
      u.pathname = u.pathname.replace(/\/+$/, "");
    }
    // Strip tracking + "redirect-after" params. The latter group catches
    // disclosure-gate / login-gate sites that redirect every URL to the same
    // gate page but encode the originally-requested URL as a query param
    // (`?next=/about`, `?next=/services`, etc.) — without stripping, each
    // worker's settled URL would look unique and dedup would miss.
    const TRACKING = /^(utm_|fbclid$|gclid$|mc_|ref$|ref_src$|_ga$|_gl$|next$|return$|return_to$|returnurl$|redirect$|redirect_to$|redirectto$|back$|back_url$|backurl$|from$|source_page$|callback$|origin$|continue$|dest$|destination$)/i;
    const keep = [];
    for (const [k, v] of u.searchParams.entries()) {
      if (!TRACKING.test(k)) keep.push([k, v]);
    }
    keep.sort((a, b) => a[0].localeCompare(b[0]));
    u.search = "";
    for (const [k, v] of keep) u.searchParams.append(k, v);
    return u.toString();
  } catch {
    return null;
  }
}

// www-insensitive hostname comparison. `www.example.com` and `example.com`
// are almost always the same site served under two names (the hosting
// provider redirects one to the other). Treating them as different sites
// meant the scope crawler would refuse to follow half the nav when the
// seed URL and the declared canonical/sitemap hostname disagreed on the
// `www.` prefix — a common cause of "only the homepage got scanned" on
// WordPress + CloudFlare setups.
//
// This is intentionally conservative — ONLY the leading `www.` is
// stripped. Other subdomains (blog.example.com, shop.example.com) stay
// distinct because they frequently ARE separate sites with separate
// audit scopes.
function stripWww(host) {
  return host && host.startsWith("www.") ? host.slice(4) : host;
}

export function sameHostname(a, b) {
  try {
    return stripWww(new URL(a).hostname) === stripWww(new URL(b).hostname);
  } catch { return false; }
}

export function sameOrigin(a, b) {
  try { return new URL(a).origin === new URL(b).origin; } catch { return false; }
}

export class RequestQueue {
  constructor({ scopeUrl, maxUrls = 50, maxDepth = 1, scope = "same-hostname" } = {}) {
    this.scopeUrl = scopeUrl;
    this.maxUrls = maxUrls;
    this.maxDepth = maxDepth;
    this.scope = scope;
    this.seen = new Set();
    // URLs that a tab actually landed on after following server redirects.
    // Tracked separately from `seen` (which is the enqueued URL set) so we
    // can skip redundant scans on disclosure-gate / age-gate / session-wall
    // sites where every URL redirects to the same landing page.
    this.settledSeen = new Set();
    this.queue = [];
    this.processed = 0;
  }

  // Dedup key for settled URLs. Two modes:
  //   • If settled pathname matches the originally-requested pathname, there
  //     was no redirect — use the full canonical URL (query params may be
  //     meaningful, e.g. pagination: /blog?page=1 vs /blog?page=2).
  //   • If settled pathname DIFFERS from the originally-requested pathname,
  //     a redirect happened. Dedup by origin + pathname only (query params
  //     on the redirected-to page are typically session/return-path hints,
  //     not content distinguishers).
  // originalRaw is optional — without it we always use pathname-only,
  // which is a conservative fallback.
  _settledKey(rawUrl, originalRaw) {
    try {
      const settled = new URL(rawUrl);
      const normPath = p => (p.length > 1 ? p.replace(/\/+$/, "") : p);
      const settledPath = normPath(settled.pathname);
      const base = settled.origin + settledPath;
      if (!originalRaw) return base;
      const original = new URL(originalRaw);
      if (normPath(original.pathname) === settledPath) {
        // No redirect — use full canonical (query params may matter)
        return canonicalize(rawUrl, this.scopeUrl);
      }
      return base;
    } catch { return null; }
  }

  hasSettled(rawUrl, originalRaw = null) {
    const key = this._settledKey(rawUrl, originalRaw);
    return key ? this.settledSeen.has(key) : false;
  }

  markSettled(rawUrl, originalRaw = null) {
    const key = this._settledKey(rawUrl, originalRaw);
    if (key) this.settledSeen.add(key);
    return key;
  }

  inScope(url) {
    if (!this.scopeUrl) return true;
    return this.scope === "same-origin"
      ? sameOrigin(url, this.scopeUrl)
      : sameHostname(url, this.scopeUrl);
  }

  enqueue(rawUrl, { depth = 0, priority = 0, source = "link" } = {}) {
    const url = canonicalize(rawUrl, this.scopeUrl);
    if (!url) return false;
    if (this.seen.has(url)) return false;
    if (!this.inScope(url)) return false;
    // Seed URL is always honoured — if a user explicitly seeds on a
    // wp-admin page or a PDF we respect that. Every other source
    // (nav/sitemap/feed/etc.) goes through the crawl-gate filter.
    if (source !== "seed" && !isCrawlablePath(url)) return false;
    if (depth > this.maxDepth) return false;
    if (this.seen.size >= this.maxUrls) return false;
    this.seen.add(url);
    this.queue.push({ url, depth, priority, source });
    // Higher priority first; ties by depth (shallower first)
    this.queue.sort((a, b) => (b.priority - a.priority) || (a.depth - b.depth));
    return true;
  }

  enqueueMany(urls, opts = {}) {
    let added = 0;
    for (const u of urls) if (this.enqueue(u, opts)) added++;
    return added;
  }

  next() {
    const r = this.queue.shift();
    if (r) this.processed++;
    return r;
  }

  get pending() { return this.queue.length; }
  get total() { return this.seen.size; }
  get remaining() { return Math.max(0, this.maxUrls - this.processed); }
}

// Per-origin adaptive rate limiter + circuit breaker.
// Start 300ms between requests per origin; 2x on 429/503, 1.5x on 5xx,
// 0.85x decay on success. 5 consecutive hard failures -> circuit tripped 60s.
export class RateLimiter {
  constructor() {
    this.state = new Map(); // origin -> { delay, nextOk, fails, breakerUntil, ok, err }
  }

  _get(origin) {
    let s = this.state.get(origin);
    if (!s) {
      s = { delay: 300, nextOk: 0, fails: 0, breakerUntil: 0, ok: 0, err: 0 };
      this.state.set(origin, s);
    }
    return s;
  }

  async wait(url) {
    let origin;
    try { origin = new URL(url).origin; } catch { return; }
    const s = this._get(origin);
    const now = Date.now();
    if (s.breakerUntil && now < s.breakerUntil) {
      // Half-open: wait the remainder, then try
      const w = s.breakerUntil - now;
      await sleep(w);
      s.breakerUntil = 0;
    }
    const wait = Math.max(0, s.nextOk - now);
    if (wait > 0) await sleep(wait);
    s.nextOk = Date.now() + s.delay;
  }

  reportSuccess(url) {
    let origin; try { origin = new URL(url).origin; } catch { return; }
    const s = this._get(origin);
    s.ok++;
    s.fails = 0;
    s.delay = Math.max(150, s.delay * 0.85);
  }

  reportFailure(url, { status = 0, retryAfterSec = 0 } = {}) {
    let origin; try { origin = new URL(url).origin; } catch { return; }
    const s = this._get(origin);
    s.err++;
    if (status === 429 || status === 503) {
      s.delay = Math.min(30000, s.delay * 2);
      if (retryAfterSec > 0) s.nextOk = Date.now() + Math.min(120000, retryAfterSec * 1000);
    } else if (status >= 500) {
      s.delay = Math.min(30000, s.delay * 1.5);
      s.fails++;
    } else {
      s.fails++;
    }
    if (s.fails >= 5) {
      s.breakerUntil = Date.now() + 60000;
      s.fails = 0;
    }
  }

  snapshot() {
    const out = {};
    for (const [o, s] of this.state) out[o] = { delay: Math.round(s.delay), ok: s.ok, err: s.err };
    return out;
  }
}

export function parseRetryAfter(value) {
  if (!value) return 0;
  const n = Number(value);
  if (Number.isFinite(n)) return Math.max(0, n);
  const d = Date.parse(value);
  if (!Number.isNaN(d)) return Math.max(0, Math.round((d - Date.now()) / 1000));
  return 0;
}

export async function retryWithBackoff(fn, { max = 4, baseMs = 1000, limiter = null, url = "" } = {}) {
  let lastErr;
  for (let attempt = 0; attempt < max; attempt++) {
    if (limiter) await limiter.wait(url);
    try {
      const r = await fn(attempt);
      if (limiter) limiter.reportSuccess(url);
      return r;
    } catch (err) {
      lastErr = err;
      const status = err?.status || 0;
      const retryAfter = err?.retryAfterSec || 0;
      if (limiter) limiter.reportFailure(url, { status, retryAfterSec: retryAfter });
      if (status && status < 500 && status !== 429 && status !== 408) throw err;
      const delay = Math.min(30000, baseMs * 2 ** attempt) + Math.random() * 300;
      await sleep(delay);
    }
  }
  throw lastErr || new Error("retry exhausted");
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }
